# Generated by Django 4.2.16 on 2024-12-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_image_alter_phone_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.CharField(default=0, max_length=6, verbose_name='price'),
            preserve_default=False,
        ),
    ]
