# Generated by Django 4.2.16 on 2024-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
