# Generated by Django 4.2.16 on 2024-12-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(max_length=10, verbose_name='price'),
        ),
    ]
